version: '3.1'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

  go:
    build: ./src
    working_dir: /go/src/go_books
    volumes:
      - ./:/go/src/go_books
    ports:
      - 8080:8080
    links:
      - db



volumes:
  db_data:
